### PR TITLE
css-brochure-form - Derren Pamintuan

### PR DESCRIPTION
**Pull request by derrenpamintuan**
localhost_5500_css-brochure-form_index html_email= name= location= hiring=1-2

### CODE REVIEW

**Review by robgmerrill — CHANGES_REQUESTED** [review]
Close! The content needs to be centered.

**Comment by derrenpamintuan** [comment]
localhost_5500_css-brochure-form_index html

**Review by robgmerrill — CHANGES_REQUESTED** [review]
👍

**Review by robgmerrill — APPROVED** [review]
👍

**Pull request merged**
